### ISSUE TITLE
Tools Directory not Automatically Created in configure.py

### ISSUE THREAD

**Issue by ameserole** [nategraf/Naumachia#25]
When running `configure.py` I get this traceback:
```
[INFO] Using config from /home/messy/Naumachia/config.yml
Traceback (most recent call last):
  File "configure.py", line 215, in <module>
    args.easyrsa = obtain_easyrsa()
  File "configure.py", line 82, in obtain_easyrsa
    installed = tuple(easyrsa_installations(tools_dir))
  File "configure.py", line 60, in easyrsa_installations
    subdirs = (subdir for subdir in (path.join(dir, name) for name in listdir(dir)) if path.isdir(subdir))
FileNotFoundError: [Errno 2] No such file or directory: '/home/messy/Naumachia/tools'
```
Creating a directory for tools fixed the issue

**Comment by nategraf** [comment]
Thanks for posting this issue!
