### ISSUE TITLE
EasyRSA Version mismatch

### ISSUE THREAD

**Issue by ReversingWithMe** [nategraf/Naumachia#27]
During build EasyRSA-3.0.5 is downloaded, dependency used as EasyRSA-3.0.4

from new python3 virtual environment, cloning repo, and pip3 install -r requirements.txt

(nau-3) auriga@auriga-VirtualBox:~/Projects/Naumachia$ sudo ./registrar-cli listen add alice
Traceback (most recent call last):
  File "./registrar-cli", line 49, in <module>
    regi.add_cert(args.client)
  File "/home/auriga/Projects/Naumachia/registrar/app/registrar.py", line 186, in add_cert
    lambda e: e.returncode == 1 and EASYRSA_ALREADY_EXISTS_MSG in e.stderr,
  File "/home/auriga/Projects/Naumachia/registrar/app/registrar.py", line 156, in _run
    **kwargs
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/auriga/Projects/Naumachia/tools/EasyRSA-3.0.4/easyrsa'

Simple workaround is moving EasyRSA-3.0.5 to EasyRSA-3.0.4 in tools directory

**Comment by ReversingWithMe** [comment]
This is on Xubuntu, which corresponds to Ubuntu 16.04

**Comment by ReversingWithMe** [comment]
registrar.py:EASYRSA = environ.get("EASYRSA", path.abspath(path.join(script_dir, '../../tools/EasyRSA-3.0.4')))

Issue is hard coded version here

**Comment by ReversingWithMe** [comment]
This code needs to be called from registrar.py

GITHUB_RELEASE_API = 'https://api.github.com/repos/OpenVPN/easy-rsa/releases/{:s}'
EASYRSA_DEFAULT=None
EASYRSA_VERSION_PATTERN=re.compile(r'(?:EasyRSA-|v)((?:\d+\.)*\d+)')
REGISTRAR_CERT_DIR=path

def easyrsa_release(tag=None, timeout=5):
    """
    Get the EasyRSA release information from github at a tag or latest if tag is None
    Returns a dictionary parsed from the GitHub release API (https://developer.github.com/v3/repos/releases/)
    """
    name = 'latest' if tag is None else 'tags/'+tag
    with requests.get(GITHUB_RELEASE_API.format(name), timeout=timeout) as resp:
        resp.raise_for_status()
        return resp.json()
